### ISSUE TITLE
UnhandledPromiseRejectionWarning - cannot run project after initial run that creates tables

### ISSUE THREAD

**Issue by vgjenks** [masumsoft/express-cassandra#164] opened 2018-06-14 17:48 UTC
I've modeled my tables and upon first run of the Node app, they all get created, as expected. If I restart the app, I get the exception. It may or may not be the issue described in the following comment:

https://github.com/3logic/apollo-cassandra/issues/8#issuecomment-291467211

Full exception stack:

```
(node:84999) UnhandledPromiseRejectionWarning: apollo.model.tablecreation.schemamismatch: Given Schema does not match existing DB Table "security_role"
warning.js:18
migration suspended, please apply the change manually
    at f (/projects/my-project/node_modules/express-cassandra/lib/orm/apollo_error.js:174:15)
    at /projects/my-project/node_modules/express-cassandra/lib/orm/base_model.js:209:16
    at /projects/my-project/node_modules/express-cassandra/lib/builders/table.js:106:11
    at /projects/my-project/node_modules/express-cassandra/lib/builders/table.js:363:9
    at /projects/my-project/node_modules/express-cassandra/lib/helpers/driver.js:59:11
    at RequestHandler.next [as _callback] (/projects/my-project/node_modules/cassandra-driver/lib/utils.js:704:14)
    at RequestHandler.setCompleted (/projects/my-project/node_modules/cassandra-driver/lib/request-handler.js:246:10)
    at responseCb (/projects/my-project/node_modules/cassandra-driver/lib/request-execution.js:84:22)
    at OperationState._swapCallbackAndInvoke (/projects/my-project/node_modules/cassandra-driver/lib/operation-state.js:145:5)
    at OperationState.setResult (/projects/my-project/node_modules/cassandra-driver/lib/operation-state.js:139:10)
    at Connection.handleResult (/projects/my-project/node_modules/cassandra-driver/lib/connection.js:573:13)
    at ResultEmitter.emit (events.js:180:13)
    at ResultEmitter.each (/projects/my-project/node_modules/cassandra-driver/lib/streams.js:501:17)
    at ResultEmitter._write (/projects/my-project/node_modules/cassandra-driver/lib/streams.js:485:10)
    at doWrite (_stream_writable.js:406:12)
    at writeOrBuffer (_stream_writable.js:392:5)
```

**Comment by masumsoft** [comment] 2018-06-15 11:14
I guess this is a duplicate of #165, closing.

**Closed by masumsoft** 2018-06-15 11:14 UTC
