### ISSUE TITLE
Throws RangeError: Index out of range during idle

### ISSUE THREAD

**Issue by bekemeps** [masumsoft/express-cassandra#109] opened 2017-05-08 09:57 UTC
The stack trace seems to be a tick_callback from the driver package...

`apollo.model.find.dberror: Error during find query on DB -> RangeError: Index out of range
    at f (/opt/app/node_modules/express-cassandra/lib/orm/apollo_error.js:174:15)
    at /opt/app/node_modules/express-cassandra/lib/orm/base_model.js:1524:16
    at /opt/app/node_modules/express-cassandra/lib/orm/base_model.js:1298:9
    at next (/opt/app/node_modules/cassandra-driver/lib/utils.js:713:14)
    at /opt/app/node_modules/cassandra-driver/lib/client.js:811:9
    at finishSettingOptions (/opt/app/node_modules/cassandra-driver/lib/client.js:1157:14)
    at next (/opt/app/node_modules/cassandra-driver/lib/utils.js:716:14)
    at Array.adaptParameterTypes (/opt/app/node_modules/cassandra-driver/lib/client.js:1137:16)
    at /opt/app/node_modules/cassandra-driver/lib/utils.js:722:21
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by masumsoft** [comment] 2017-05-08 11:52
Which version of express-cassandra you're using? A datastax driver related issue was resolved in the latest version. It's difficult to reproduce the issue without further information from you. Sharing the versions of node and express-cassandra you're using, and part of the code where you've initialised express-cassandra would be helpful.

**Comment by masumsoft** [comment] 2017-05-15 06:22
closing due to inactivity

**Closed** 2017-05-15 06:22 UTC
