### ISSUE TITLE
All host(s) tried for query failed. First host tried, host:port ResponseError: Beta version of the protocol used (5/v5-bet

### ISSUE THREAD

**Issue by KARTIK01** [masumsoft/express-cassandra#103] opened 2017-04-21 11:20 UTC
All host(s) tried for query failed. First host tried, host:port ResponseError: Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset. See innerErrors.

This error coming of last 2 days.
And later i figure it out. express-cassandra is using [dse-driver](https://github.com/datastax/nodejs-dse-driver) in its dependencies.
 ```dse-driver": "^1.1.0"```

and dse-driver updated on 18th to [version 1.3.0](https://github.com/datastax/nodejs-dse-driver/blob/master/CHANGELOG.md) due to which this error is coming.

Please fix package.json or fix this issue.

**Comment by adnan-kamili** [comment] 2017-04-21 13:21
I am also facing the same issue, it suddenly started appearing.  Allowing minor version update for **dse-driver** is a blunder. Had our code been in production (which it is about to) it would have caused havoc.

**Comment by masumsoft** [comment] 2017-04-21 15:08
I also faced this issue yesterday. According to [semantic versioning standard](https://docs.npmjs.com/getting-started/semantic-versioning) adopted by node, allowing minor version upgrade in package.json should be safe! npm also defaults to this. But it looks like the dse-driver had published an update backwards incompatible, but with minor version increment, which violates the semantic versioning standards and the cause for this catastrophe. Anyways, I'm going to publish a fix within short time.

**Comment by masumsoft** [comment] 2017-04-21 17:43
Fixed now in v1.8.2

**Closed by masumsoft** 2017-04-21 17:43 UTC
