### ISSUE TITLE
UDT getting saved every time my application restarts.

### ISSUE THREAD

**Issue by amanpurohit** [masumsoft/express-cassandra#55] opened 2016-06-30 08:18 UTC
I have defined my udts in app.js file under orm options which gets called every time the application reloads. I get this error `User defined type 'type_name' already exists`. Is there a way to turn off the mechanism to add udts once it is created. Right now I am running my script containing udt definitions manually.

**Comment by masumsoft** [comment] 2016-06-30 09:22
Could you please provide some code example of actually how you've implemented udts and which version of express-cassandra you are using? The udts are only created if they do not exist. But if the udt exist and your definition in the app.js does not match the actual cassandra udt, then an error would be thrown.

**Comment by amanpurohit** [comment] 2016-07-01 10:32
I am using version 1.0.3. 
In my app.js I am using the following piece of code.
`ormOptions: {
      udts : {
        phone: {
          number: "varchar",
          isVerified: "boolean"
        }
      },
      defaultReplicationStrategy : {
        class: 'SimpleStrategy',
        replication_factor: 1
      }`

**Comment by masumsoft** [comment] 2016-07-04 16:18
I did create some test cases with your phone schema and it works fine at my end. Btw, I can see a missing } at the end of ormOptions in your example. Whatever, assuming it's not present in your actual implementation, I would like to ask for more information of your setup, like the cassandra version you are using. I'm testing using cassandra 3.0.x and it works fine at my end.

**Comment by masumsoft** [comment] 2016-07-20 09:20
Closing this as the issue could not be reproduced and no activities since then.

**Closed by masumsoft** 2016-07-20 09:20 UTC
